export interface TrackLineOfItems {
    "country_of_origin": string,
    "customer_id": string,
    "dispatch_number": string,
    "exp_delivery_time": string,
    "liveTrackingEligible": string,
    "order_id": string,
    "order_placed": string,
    "product_service_code": string,
    "recepient_dtls": {
        "building_no": string,
        "city": string,
        "email": string,
        "first_name": string,
        "floor": string,
        "last_name": string,
        "middle_name": string,
        "mobileNo": string,
        "po_box_no": string,
        "postal_code": string,
        "qatar_id": string,
        "region": string,
        "street_name": string,
        "street_no": string,
        "town": string,
        "zone": string
    },
    "receptacle_number": string,
    "signatory_id": string,
    "signatory_mobile": string,
    "signatory_name": string,
    "sla_in_hours": string,
    "track_facility": string,
    "tracking_number": string
}